nezn00-cv04
nvbach91/4IZ278-2022-2023-LS pull request #145
Opened 2023-03-16 16:13 UTC by Nezn00

odovzdavam cv04
esotemp- https://esotemp.vse.cz/~nezn00/cv04/

2023-03-16 23:17 UTC, nvbach91 requested changes

2023-03-16 23:17 UTC, nvbach91 commented on www/nezn00/cv04/registration-form.php
> +        header("Location: login.php?$email");
?email=$email

2023-03-16 23:17 UTC, nvbach91 commented on www/nezn00/cv04/registration-form.php
> +        file_put_contents($databaseFilePath, $userRecord, FILE_APPEND);
soubor neobsahuje nove registrovane uzivatele

2023-03-17 11:49 UTC, Nezn00 commented
database opravena zabudol som dat povolenie cez winscp

2023-03-17 15:25 UTC, nvbach91 approved these changes

2023-03-17 15:25 UTC, merged