voll03-cv01
nvbach91/4IZ278-2022-2023-LS pull request #18
Opened 2023-02-21 19:36 UTC by voll03

Odevzdávám úkol z 1. cvičení.
Odkaz na eso: https://esotemp.vse.cz/~voll03/cv01/

2023-02-24 13:50 UTC, nvbach91 requested changes

2023-02-24 13:50 UTC, nvbach91 commented on www/voll03/cv01/index.php
> +                    echo "<p><a href=tel:" . $phone . ">" . $phone . "</a></p>";
html tagy davame mimo php echo

2023-02-24 13:50 UTC, nvbach91 commented on www/voll03/cv01/index.php
> +                    echo "<p><a href=mailto:" . $email . ">" . $email . "</a></p>";
nevalidni HTML

2023-02-24 13:50 UTC, nvbach91 commented on www/voll03/cv01/index.php
> +                    echo "<p>" . $street . "</p>";
HTML tagy nikdy nedavame do stringu

2023-02-25 12:16 UTC, voll03 commented
opraveno

2023-02-25 15:06 UTC, nvbach91 approved these changes

2023-02-25 15:07 UTC, merged