tolo00-sp
nvbach91/4IZ278-2022-2023-LS pull request #203
Opened 2023-04-08 13:45 UTC by ondrej-tolg

Aplikace je dostupná na URL: https://js-semestralka.incolorstudio.cz/

2023-05-24 15:23 UTC, nvbach91 requested changes
Muzete me prosím pridat jako developera nebo testera ve Vasi aplikaci na facebook developers? fbid = 1832572360

![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/0615d1b6-ebf3-4445-8c64-7bf8a1c539d0)

2023-05-24 17:05 UTC, ondrej-tolg commented
@nvbach91 přidal jsem Vás.

V pátek mám u Vás obhajobu v 10 hod, v 11 hod mám další obhajobu z XML, myslíte, že to stihneme? U toho XML se mi moc nepovedl test, takže na tu obhajobu bych určitě potřeboval dorazit. (doslechl jsem se, že se obhajoba u Vás může protáhnout až na několik hodin 😅). Myslíte, že to stihneme, nebo bych se měl radši s p. Vojířem nějak domluvit, že se mohu zpozdit? Děkuji

2023-05-24 17:06 UTC, ondrej-tolg commented
A feedback co od Vás dostanu mám zapracovat na obhajobě, nebo mohu ještě před ní?

2023-05-25 11:48 UTC, nvbach91 requested changes
Bude potreba abyste dodelal/opravil:
- indikaci toho zda aktualni uzivatel necemu konkretnimu dal like, ted je tam videt jen pocet like, ale neni poznat ze aktualni uzivatel tomu like daval nebo ne
- tlacitko reply pri vicenasobnem klikani
- filtraci prispevku podle tagu, + klikanim na tag zobrazit prispevky s danym tagem
- pokud byl prispevek upravovan, zobrazit datum a cas posledni zmeny
- palubni desku se statistikou o poctu prispevku, lajku, uzivatelu podle tagu
- no a aby se tam nikdo jen tak nedostal

heslo Abcd1234

2023-05-25 11:48 UTC, nvbach91 commented on www/tolo00/sp/config/deploy/deployment.dev.php
> +$PASSWORD = 'WvE7VV79SbjoX5lDzP1Z';
hodne bezpecne

2023-05-25 14:59 UTC, ondrej-tolg commented
Feedback jsem zapracoval (nenahrál jsem sem, je to ošemetné), tak zítra to můžeme na obhajobě projít 👍

2023-05-26 08:45 UTC, ondrej-tolg commented
@nvbach91 změny jsem nahrál na https://js-semestralka.incolorstudio.cz/.

Mám je nahrát i sem na github? Já na to nějak nemůžu přijít jak se to dělá

2023-05-26 09:11 UTC, nvbach91 commented
Ano, kód nahrát sem na tuto branch, návod viz wiki

2023-05-26 10:54 UTC, ondrej-tolg commented
@nvbach91 hotovo

2023-05-26 11:06 UTC, nvbach91 approved these changes

2023-05-26 11:06 UTC, merged