chet01-sp-pilot
nvbach91/4IZ278-2022-2023-LS pull request #300
Opened 2023-05-12 08:29 UTC by t-chess

https://esotemp.vse.cz/~chet01/sp/
Zatím funguje jen registrace, login a jednoduchý výpis blokovaných míst pro datum

2023-05-15 20:39 UTC, t-chess commented
upd: rozhraní pro "zákazníky" je víceméně hotové, jde přidat rezervaci, zobrazit seznam všech svých rezervací, upravit nebo smazat rezervace, upravit své údaje, změnit heslo
chtěla bych se jen zeptat, jak velká část hodnocení bude za FE, jestli by stačil takový jak ho mám teď nebo by to chtělo něco sofistikovanější? díky

2023-05-23 20:45 UTC, t-chess commented
upd: finální verze

2023-05-25 13:07 UTC, nvbach91 requested changes
- seznam rezervaci v My reservations by mel byt serazen podle datumu
- muzete jeste dodelat view kde bude videt ktere dny jsou volne pro konkretni stul nebo mistnost?
- chybi oauth

2023-05-25 19:18 UTC, t-chess commented on www/chet01/sp/api/ReservationModel.php
> +        $table = $data['table'];
to by pak chtělo proměnnou která by ukládala délku rezervace v hodinách, což by pak zkomplikovalo hodně jiných věcí a přišlo mi to trochu jako overkill

2023-05-25 19:19 UTC, t-chess commented
@nvbach91 všechno kromě oauth je opravené

2023-05-26 10:22 UTC, nvbach91 approved these changes

2023-05-26 10:22 UTC, merged