kulm11-sp
nvbach91/4IZ278-2022-2023-LS pull request #311
Opened 2023-05-14 11:40 UTC by MichK28

Odevzdávám pilotní verzi semestrální práce. Je připravena databáze, otestováno připojení k databázi pomocí testovací položky, připraveny formuláře pro login a signup. Odkaz: https://esotemp.vse.cz/~kulm11/sp

2023-06-21 08:03 UTC, MichK28 commented
Přihlašovací údaje pro administrátora:
admin@admin.com
123123

2023-06-21 19:45 UTC, nvbach91 commented
opravte oauth 
![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/2c3e07cf-b49f-43d7-a6de-e093da5cc73f)
 a pak me pridejte jako testera do facebook app  fbid = 1832572360

![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/0615d1b6-ebf3-4445-8c64-7bf8a1c539d0)

2023-06-21 19:58 UTC, nvbach91 requested changes

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/index.php
> +                    echo '<li><a href="./signup.php">Sign up</a></li><li><a href="./login.php">Login</a></li>';
html nedavame do echo

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/checks/signupCheck.php
> +        header("Location: ./login.php");
po uspesne registraci bez potvrzeni/hlasky?

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/checkout.php
> +                                <p><strong><?php echo $item["name"]; ?></strong></p>
chtelo by to tabulku srovnat...

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/createOrder.php
> +    session_start();
chybi rekapitulace objednavky (dorucovaci adresa)

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/orderhistory.php
> +                            <td><?php echo $item["name"]; ?></td>
pridat odkaz na produkt

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/orderhistory.php
> +                <p class="total-price"><strong>Total: <?php echo $totalPrice; ?></strong></p>
neni strankovani

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/remove.php
> +        $usersDatabase->removeUser(htmlspecialchars($_GET["user_id"]));
```
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 
1451 Cannot delete or update a parent row: a foreign key constraint fails 
(`kulm11`.`Order`, CONSTRAINT `order_user_fk` FOREIGN KEY (`user_userid`) 
REFERENCES `User` (`userid`)) in /home/httpd/html/users/kulm11/sp/database/UsersDatabase.php:106 Stack trace: 
#0 /home/httpd/html/users/kulm11/sp/database/UsersDatabase.php(106): 
PDOStatement->execute() #1 /home/httpd/html/users/kulm11/sp/remove.php(19): 
UsersDatabase->removeUser() #2 {main} thrown in 
/home/httpd/html/users/kulm11/sp/database/UsersDatabase.php on line 106

```

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/orderhistory.php
> +                        <?php $item = $itemsDB->fetch($orderedItem["item_itemid"]); ?>
`Warning: Trying to access array offset on value of type bool in /home/httpd/html/users/kulm11/sp/orderhistory.php on line 68` - po smazani produktu

2023-06-21 19:58 UTC, nvbach91 commented on www/kulm11/sp/add.php
> +                <input type="email" name="email">
chybi vraceni vyplenych poli

2023-06-22 18:04 UTC, nvbach91 commented
- tlacitko cancel data not found
- nechodí emaily

2023-06-23 08:34 UTC, nvbach91 commented
- napojeni items, a ordered items
- obratit poradi objednavek
- nesedi obsah kosiku s obejednavkou pri vyberu vice polozek
- delete confirm

2023-06-23 10:17 UTC, nvbach91 approved these changes

2023-06-23 11:19 UTC, merged