vitd04-sp
nvbach91/4IZ278-2022-2023-LS pull request #312
Opened 2023-05-14 11:49 UTC by KingDoxik

Odevzdávám pilotní verzi semestrální práce. Mám zárodek frontendu a backendu, vytvřenoé knihovny pro komunikaci mezi api a frontendem. Přihlašování přes Laravel Sanctum. V nasazené verzi na esotemp zatím bohužel nefunguje, řeším problém s CSFR. Je také vytvořeny migrace a modely pro databázi. frontend: https://kam-za-jidlem.vercel.app api: https://esotemp.vse.cz/~vitd04/sp/

2023-05-30 19:59 UTC, KingDoxik commented
Odevzdávám svojí semestrální práci. Finální verze je dostupná na https://4iz278.kamzajidlem.cz/ a Laravel API běží na https://server.4iz278.kamzajidlem.cz/ OpenID je přes Google, který mi fungoval i bez přidání účtu do seznamu povolených, ale pokud by s tím byl problém, tak vás tam manuálně přidám.

2023-06-01 14:27 UTC, nvbach91 requested changes
- Aplikace je hodne buggy, nektera tlacitka nereaguji, seka to pri prepinani mezi strankami, nektere operace pridani se nepodari udelat napoprve, atd.
- navigace v adminu je slozita (musi se pouzivat browser tlacitko zpet)
- vyhledavac: proc tam jde dat jenom Prahu a Brno?
- Pres google mi to neslo napoprve
- dalsi veci viz nize

2023-06-01 14:27 UTC, nvbach91 commented on www/vitd04/sp/apps/laravel/routes/api.php
> +    Route::middleware(['auth:sanctum'])->post('/menu-items', 'store');
![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/77dfbfe0-16c9-46ae-9e7a-c2f61fc1293a)

2023-06-02 09:43 UTC, nvbach91 approved these changes

2023-06-02 09:43 UTC, merged