bigc00-sp
nvbach91/4IZ278-2022-2023-LS pull request #314
Opened 2023-05-14 15:25 UTC by bigc00

https://esotemp.vse.cz/~bigc00/sp

2023-06-01 13:34 UTC, nvbach91 requested changes
Bude potřeba dodělat/opravit následující věci:
- struktura souborů - viz komentáře
- zabezpečení aplikace pomocí htaccess
- seo URL pomoci htaccess
- emailová notifikace pro prijemce platby
- OAuth

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/Utils.php
> +            $errors['password'] = "Password Must Contain At Least 8 Characters!";
popis neodpovida regex

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/includes/accounts.php
> +<?php
chybi kontrola user login

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/index.php
> +isset($_SESSION['user']) ? header('Location: ./includes/accounts.php') : header('Location: ./includes/main.php');
stranky accounts, history, login, main, newAccount, newPayment, registration nepatri do slozky includes

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/includes/registration.php
> +                    <a class='grey' id='success' href='./login.php'>You have successfully signed up!</a>
po uspesne registraci presmerovat na login automaticky, nebo zobrazit odkaz na login

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/includes/newPayment.php
> +$categories = [
tyto typy plateb patri v databazi a transakce na ne budou referencovat pomoci ID

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/includes/adminPanel.php
> +                    <option <?php echo $type == 'Current account' ? 'selected' : '' ?>>Current account</option>
tyto typy uctu patri v databazi a ucty budou na ne referencovat pomoci id

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/database/AccountsDB.php
> +        $sql = "INSERT INTO `accounts`(`account_id`, `name`, `owner_id`, `balance`, `account_type`)
`accounts` se tady objevuje na vice mistech

2023-06-01 13:34 UTC, nvbach91 commented on www/bigc00/sp/database/TransactionsDB.php
> +        $sql = "INSERT INTO `transactions`(`sender_id`, `recipient_id`, `amount`, `category`)
`transactions` se objevuje na vice mistech

2023-06-21 17:15 UTC, nvbach91 commented
@bigc00 něco nového v projektu?

2023-06-21 18:13 UTC, nvbach91 commented
A co takhle odevzdat vcas a doladit to potom?

2023-06-21 20:08 UTC, bigc00 commented
Dobře , už to udělala

Ср, 21 июня 2023 г. в 20:14, Nguyen Viet Bach ***@***.***>:

> A co takhle odevzdat vcas a doladit to potom?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nvbach91/4IZ278-2022-2023-LS/pull/314#issuecomment-1601349778>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6HR7WWACZI2DARIQ6KYGKLXMM2WZANCNFSM6AAAAAAYBHF4LE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-21 20:19 UTC, nvbach91 commented
muzete mi dat odkaz do nove aplikace?

2023-06-22 15:59 UTC, bigc00 commented
https://esotemp.vse.cz/~bigc00/sp/

2023-06-23 07:27 UTC, nvbach91 commented
- chybi M:N vztah

2023-06-23 21:54 UTC, bigc00 commented
# Vzdělávací centrum
E-Shop vzdělavacího centru
### Funkcionalita
* Řazení podle kategorií zboží
* Posuvník zboží na akci
* Přidání zboží do košíku
* Vytvoření profilu pro usnadnění dálší nákupů
* Možnost autorizáce přes Google
### [Usecase Diagram](https://imgur.com/a/6rMXz1g)
---
## Technologie
### Architektura

* WebServer: Apache
* BackEnd: PHP 8
* Database: MySQL
* FrontEnd: HTML + CSS + JS
### Wireframe
* [Home page - Akční zboží ve slideru, seznam všech zboží](https://imgur.com/a/SJptmF5)
* [Admin panel](https://imgur.com/a/32r71XZ)
* [Profile](https://imgur.com/a/8YVM1Dj)
* [Cart](https://imgur.com/a/LEgGXdQ)

### Database
* Admins
* User
* Courses
* Orders
* Orderinfo

#### [Logický model](https://imgur.com/a/jSU2ARr)

#### [Fizický model](https://imgur.com/a/m5R9vQT) 

### [Procesní diagram](https://imgur.com/a/FFisYoz)

### [Sekvenční diagram](https://imgur.com/a/kt98h3D)

2023-06-24 07:26 UTC, nvbach91 commented
- ve schematu chybi tabulka category
- v tabulce orderinfo chybi price
- v tabulce orders chybi informace o objedateli
- tabulka admins je zbytecna, staci do tabulky users dat atribut admin

2023-06-24 07:43 UTC, bigc00 commented
Dobry den ,dobře ,opravím.

Сб, 24 июня 2023 г. в 09:26, Nguyen Viet Bach ***@***.***>:

>
>    - ve schematu chybi tabulka category
>    - v tabulce orderinfo chybi price
>    - v tabulce orders chybi informace o objedateli
>    - tabulka admins je zbytecna, staci do tabulky users dat atribut admin
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nvbach91/4IZ278-2022-2023-LS/pull/314#issuecomment-1605297307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6HR7WSSSYQBC3HQDFVPPV3XM2JB3ANCNFSM6AAAAAAYBHF4LE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-24 21:59 UTC, bigc00 commented
#### [Logický model](https://imgur.com/a/PTkh4lY)

#### [Fizický model](https://imgur.com/a/kJRSAlY)

2023-06-24 22:04 UTC, nvbach91 approved these changes

2023-06-24 22:04 UTC, merged