staj20-sp
nvbach91/4IZ278-2022-2023-LS pull request #323
Opened 2023-05-14 20:48 UTC by psaniac

Pilotní verze semestrální práce
Dostupná z:
https://esotemp.vse.cz/~staj20/sp/

Stránky vypadají víc funkční než jsou, například stránka s produkty je statická, ale ve finální verzi bude generovaná z dat z databáze.

2023-05-18 14:43 UTC, nvbach91 requested changes

2023-05-18 14:43 UTC, nvbach91 commented on www/staj20/sp/assets/config/db-access.php
> +const DB_PASSWORD = 'iengu4oRaqu4siezae';
![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/43dd1bde-6a99-4599-ad6f-6e1973bb2015)

2023-06-23 10:42 UTC, psaniac commented
Odevzdána finální verze semestrální práce po obhajobě.

2023-06-23 11:19 UTC, nvbach91 approved these changes

2023-06-23 11:20 UTC, merged