trep01-sp
nvbach91/4IZ278-2022-2023-LS pull request #325
Opened 2023-05-14 21:15 UTC by blbin

Raná pilotní verze samostatné práce. 
Odkaz na server:
https://patriktrejtnar.cz/ftpclient

Obsahuje strukturu souborů a složek + základní třídy potřebné pro komunikaci s databází.

2023-06-14 12:28 UTC, nvbach91 commented
Prosim o nejaka testovaci data (login)

2023-06-14 12:29 UTC, nvbach91 requested changes
- Chybi kontrola existence uzivatele pri registraci
- Chybi oauth

2023-06-14 12:32 UTC, blbin commented
> Prosim o nejaka testovaci data (FTP login)

server: 26715.s15.wedos.net
Username: s26715
Password: F17345.p

2023-06-16 08:23 UTC, nvbach91 commented
- tlacitka u kazde polozky (preview, download)

2023-06-16 12:44 UTC, nvbach91 approved these changes

2023-06-16 12:44 UTC, merged