mudp01-sp
nvbach91/4IZ278-2022-2023-LS pull request #326
Opened 2023-05-14 21:20 UTC by Petr-Mudra

SP bude pravděpodobně dělaná v laravelu, ale mám s tím zatím problémy, takže sem alespoň zatím dávám NElaravel kostru... V esotemp phpadmin vytvořena databáze s relacemi dle dokumentace, pdo připojení na databázi, základní kostra souborů, nějaká landing page...

2023-05-18 14:44 UTC, nvbach91 requested changes

2023-05-18 14:44 UTC, nvbach91 commented on www/mudp01/sp/config/config.php
> +const DB_PASSWORD = 'di9quohf9eexai7Eej';
![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/b46f5982-48a0-407b-8f6f-afef0e8aa74b)

2023-06-14 19:05 UTC, Petr-Mudra commented on www/mudp01/sp/config/config.php
> +const DB_PASSWORD = 'di9quohf9eexai7Eej';
Vyřešeno.

2023-06-14 19:06 UTC, Petr-Mudra commented
Zapoměl jsem dát link na app: https://esotemp.vse.cz/~mudp01/SP/

2023-06-15 11:20 UTC, Petr-Mudra commented
@nvbach91 mohu tedy přijít?

2023-06-16 09:48 UTC, nvbach91 commented
- order item price
- filter orders paid, vs not paid
- opsat puvodni hodnoty formulate pokud neprochazi
- select category options

2023-06-16 12:41 UTC, nvbach91 approved these changes

2023-06-16 12:41 UTC, merged