nezn00-sp
nvbach91/4IZ278-2022-2023-LS pull request #336
Opened 2023-05-16 21:24 UTC by Nezn00

Odovzdávam pilotnú verziu mojej semestrálnej práce kod je zatial trochu špagetový ale to všetko neskor upravím

2023-05-18 14:51 UTC, nvbach91 requested changes

2023-05-18 14:51 UTC, nvbach91 commented on www/nezn00/semestralka/database.php
> +$pass = 'eeti9Cheiyiebu4aij';
heslo nedavame na git...

2023-05-18 15:37 UTC, Nezn00 commented on www/nezn00/semestralka/database.php
> +$pass = 'eeti9Cheiyiebu4aij';
Dobre, opravené.

2023-05-18 15:39 UTC, nvbach91 commented on www/nezn00/semestralka/database.php
> +$pass = 'eeti9Cheiyiebu4aij';
To uz je stejne pozde :'(

2023-05-18 15:40 UTC, Nezn00 commented on www/nezn00/semestralka/database.php
> +$pass = 'eeti9Cheiyiebu4aij';
prečo pozde?

2023-06-13 22:31 UTC, Nezn00 commented
neišlo mi editnúť tento pull request tak som moju pilotnú verziu odovzdal ako nový pull request

2023-06-14 12:04 UTC, nvbach91 commented
Prosim o odkaz na aplikaci

2023-06-14 12:44 UTC, Nezn00 commented
prosím vás ako ma vyzerat  host, db_name a user v configu vo winscp aby mi to išlo?

2023-06-14 13:13 UTC, nvbach91 commented
- https://esotemp.vse.cz/info/
- https://github.com/nvbach91/4IZ278-2022-2023-LS/wiki/P-esotemp.vse.cz
- https://github.com/nvbach91/4IZ278-2022-2023-LS/tree/master/www/nguv03/cv05

2023-06-14 15:33 UTC, nvbach91 commented
Problém bude spíš v tom, že v databázi na serveru nemáte nic.

2023-06-14 15:37 UTC, Nezn00 commented
aha už chápem idem to naimportovat

2023-06-16 08:04 UTC, nvbach91 commented
- order item price
- vztah order a users
- edit product jako create
- order date
- oauth

2023-06-16 12:42 UTC, closed without merging