mikd08-sp
nvbach91/4IZ278-2022-2023-LS pull request #338
Opened 2023-05-18 15:54 UTC by ysdmikula

Pilotní verze sp bez souborů pro fb auth.

2023-05-29 17:12 UTC, ysdmikula commented
https://esotemp.vse.cz/~mikd08/sp/index.php

2023-06-01 13:42 UTC, nvbach91 requested changes
Muzete me prosím pridat jako developera nebo testera ve Vasi aplikaci na facebook developers? fbid = 1832572360

![image](https://github.com/nvbach91/4IZ278-2022-2023-LS/assets/20724910/0615d1b6-ebf3-4445-8c64-7bf8a1c539d0)

Bude potřeba dodělat/opravit následující věci:
- formátování ceny
- otestovat aplikaci na produkci - esotemp...
- opravit komentáře níže

2023-06-01 13:42 UTC, nvbach91 commented on www/mikd08/sp/index.php
> +        "http://localhost/www/mikd08/sp/fb/fb-login-callback.php", $permissions
nespravny odkaz

2023-06-01 13:42 UTC, nvbach91 commented on www/mikd08/sp/products.php
> +                        <a href="/www/mikd08/sp/customer/buy.php?product_id=<?php echo htmlentities($product["product_id"])?>" class="card-link addToCart-link" id="buy-btn">Add to cart</a>
nespravny odkaz, používejte spíše relativní odkazy...

2023-06-01 13:42 UTC, nvbach91 commented on www/mikd08/sp/profile.php
> +        header("Location: /www/mikd08/sp/index.php");
nesprávný odkaz

2023-06-01 13:42 UTC, nvbach91 commented on www/mikd08/sp/notLogged.js
> +    xhr.open("POST", "/www/mikd08/sp/register.php", true);
nespravny odkaz, nelze se zaregistrovat

2023-06-01 19:27 UTC, ysdmikula commented
https://esotemp.vse.cz/~mikd08/sp/index.php

2023-06-02 09:40 UTC, nvbach91 commented
@ysdmikula potřebuju commit z obhajoby

2023-06-02 11:05 UTC, ysdmikula commented
commit proveden

2023-06-03 10:48 UTC, nvbach91 approved these changes

2023-06-03 10:48 UTC, merged