vikd00-sp
nvbach91/4IZ278-2022-2023-LS pull request #342
Opened 2023-05-20 18:39 UTC by vikd00

Pilotná verzia semestrálnej práce - aplikácie ReDrive 

Link na esotemp: https://esotemp.vse.cz/~vikd00/sp/

Zatiaľ iba landing page, doťahovanie potrebných dát z databázy a základná štruktúra súborov/priečinkov.

2023-06-14 05:14 UTC, vikd00 commented
Vzhľadom na problémy s prepájaním PHP skriptov a načítavaním zdrojových súborov na EsoTempe, som prešiel na flat file structure. V prípade záujmu môžem ukázať aj verziu v pôvodnej štruktúre súborov.

2023-06-14 12:37 UTC, nvbach91 requested changes
- fulltext search nefunguje
- u paliva, prevodovky,  bude lepsi select + option
- zobrazit nahled aktualniho obrazku v editaci inzeratu
- XSS vulnerable

2023-06-14 15:36 UTC, vikd00 commented
Opravene nedostatky v poslednom commite
- opraveny fulltext search
- pridane select/options na prevodovku a palivo
- pridany nahlad aktualneho obrazku v edite, prv ulozene v databaze a nasledne toho ktory sme nahrali
- opravene XSS slabiny
- pridana validacia numerickych hodnot

2023-06-16 08:33 UTC, nvbach91 commented
- chat time
- integrity constraint when deleting user
- cas zpravy
- upozorneni na nove zpravy

2023-06-16 10:22 UTC, vikd00 commented
Posledny commit -> verzia po obhajobe s casom sprav, notifikaciami a opravenym mazanim

2023-06-16 12:44 UTC, nvbach91 approved these changes

2023-06-16 12:44 UTC, merged