vejm04-cv01
nvbach91/4IZ278-2022-2023-LS pull request #41
Opened 2023-02-24 09:56 UTC by VejsadaMatej

Odevzdavam cviceni 01
odkaz na server eso: https://esotemp.vse.cz/~vejm04/cv01/bc.php

2023-02-24 14:17 UTC, nvbach91 requested changes

2023-02-24 14:17 UTC, nvbach91 commented on www/vejm04/cv01/bc.php
> +    <head>
nevalidni HTML

2023-03-01 17:17 UTC, VejsadaMatej commented on www/vejm04/cv01/bc.php
> +    <head>
opraven tag img, online validator html již nehlásí žádnou jinou chybu

2023-03-02 22:04 UTC, nvbach91 commented on www/vejm04/cv01/bc.php
> +    <head>
@VejsadaMatej a co `<html>` tag?

2023-03-03 09:01 UTC, VejsadaMatej commented on www/vejm04/cv01/bc.php
> +    <head>
@nvbach91 doplněn lang

2023-03-05 22:47 UTC, nvbach91 approved these changes

2023-03-05 22:48 UTC, merged